### ISSUE TITLE
esp32_64 toolchain fails due to missing cc1

### ISSUE THREAD

**Issue by rohansingh** [iotaledger/toolchains#14]
Compiling the tests with the the ESP32 toolchain doesn't seem to work:

```
$ bazel build --config=esp32_64 //tests:hello
...
ERROR: /home/rohan/code/toolchains/tests/BUILD:3:1: C++ compilation of rule '//tests:hello' failed (Exit 1) xtensa-esp32-elf-gcc failed: error executing command tools/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0/xtensa-esp32-elf/xtensa-esp32-elf-gcc -nostdinc -nostdlib '--sysroot=xtensa_esp32_elf_linux64/xtensa-esp32-elf/sysroot' -isystem ... (remaining 35 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
xtensa-esp32-elf-gcc: error trying to exec 'cc1': execvp: No such file or directory
Target //tests:hello failed to build
```

It looks like `cc1` is provided in the xtensa toolchain at `libexec/gcc/xtensa-esp32-elf/5.2.0/cc1`. However, this doesn't seem to be available at compile-time.

Did this work previously? It's not clear to me if something changed that broke it. I'm looking into it on my end, but my expertise with Bazel toolchains is limited.

**Comment by oopsmonk** [comment]
The `//tests:hello` doesn't work on esp32 toolchain, the error is caused by the entry function `main()`, it's called `app_main()` in the esp32.
This esp32 toolchain helps us to build libraries, not binaries. if you want to build a binary you should use [esp-idf](https://github.com/espressif/esp-idf) or [arduino-esp32](https://github.com/espressif/arduino-esp32).

**Comment by rohansingh** [comment]
Yeah, that makes sense. For more context, I'm looking into Bazel-ifying the entire ESP-IDF so that we can use Bazel instead of the `make`/`cmake`-based build system in ESP-IDF.

For what it's worth, the `cc_library` at `//tests:hi` fails in the exact same way for me. I'm probably just going to regenerate the toolchain from scratch, but if you have any examples of even a library build that works with `--config=esp32_64`, I'd be much obliged.

**Comment by oopsmonk** [comment]
> Yeah, that makes sense. For more context, I'm looking into Bazel-ifying the entire ESP-IDF so that we can use Bazel instead of the `make`/`cmake`-based build system in ESP-IDF.
> 
> For what it's worth, the `cc_library` at `//tests:hi` fails in the exact same way for me. I'm probably just going to regenerate the toolchain from scratch, but if you have any examples of even a library build that works with `--config=esp32_64`, I'd be much obliged.

Sorry for replying late. it's odd, what is your Bazel version? I'm using 0.27.0.

```
$ bazel build --config=esp32_64 //tests:hi
INFO: Analyzed target //tests:hi (14 packages loaded, 1630 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/sam/.cache/bazel/_bazel_sam/0d61143c1f64c28426c537a121aa183d/sandbox
Target //tests:hi up-to-date:
  bazel-bin/tests/libhi.a
INFO: Elapsed time: 5.386s, Critical Path: 0.28s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed successfully, 4 total actions
```

**Comment by rohansingh** [comment]
I'm using Bazel v0.27.0. Given that `//tests:hi` builds just fine for you, I figured there might be something wrong with my environment. However, I can repro the issues with a Google-provided Docker image as well:

```
$ docker run --entrypoint bash -it l.gcr.io/google/bazel:0.27.0

# apt-get update && apt-get -y install build-essential
# git clone https://github.com/iotaledger/toolchains
# cd toolchains

# bazel build --config=esp32_64 //tests:hi
INFO: Analyzed target //tests:hi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /toolchains/tests/BUILD:9:1: C++ compilation of rule '//tests:hi' failed (Exit 1) xtensa-esp32-elf-gcc failed: error executing command tools/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0/xtensa-esp32-elf/xtensa-esp32-elf-gcc -nostdinc -nostdlib '--sysroot=xtensa_esp32_elf_linux64/xtensa-esp32-elf/sysroot' -isystem ... (remaining 31 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
xtensa-esp32-elf-gcc: error trying to exec 'cc1': execvp: No such file or directory
Target //tests:hi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.347s, Critical Path: 0.11s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Here is the `lsb-release` from that Docker image:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

Is it possible that there's some dependency in your environment that's needed for the build, and that's somehow leaking into the Bazel sandbox?

**Comment by mgrabatin** [comment]
I've also run into this issue yesterday and it seems to me that a PATH entry to the xtensa binaries is missing.
Adding this path as shown below lets the compilation finish successfully, though there probably is a way better place to add this PATH entry using bazel.

```
$ docker run --entrypoint bash -it l.gcr.io/google/bazel:0.27.0

# apt-get update && apt-get -y install build-essential
# git clone https://github.com/iotaledger/toolchains
# cd toolchains

# sed -i '2iexport PATH=$(pwd)/external/xtensa_esp32_elf_linux64/bin' tools/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0/xtensa-esp32-elf/xtensa-esp32-elf-gcc
# cat tools/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0/xtensa-esp32-elf/xtensa-esp32-elf-gcc
#!/bin/bash --norc
export PATH=$(pwd)/external/xtensa_esp32_elf_linux64/bin

exec -a xtensa-esp32-elf-gcc \
    external/xtensa_esp32_elf_linux64/bin/xtensa-esp32-elf-gcc \
    "$@"

# bazel build --config=esp32_64 //tests:hi
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tests:hi (14 packages loaded, 1630 targets configured).
INFO: Found 1 target...
Target //tests:hi up-to-date:
  bazel-bin/tests/libhi.a
INFO: Elapsed time: 32.008s, Critical Path: 0.35s
INFO: 2 processes: 2 processwrapper-sandbox.
INFO: Build completed successfully, 4 total actions
```

**Comment by oopsmonk** [comment]
@rohansingh @mgrabatin thanks for your report and help.

**Comment by rohansingh** [comment]
This exact same error seems to have popped back up with Bazel v1.0.0+. Everything works perfectly on v0.29.0, but fails on v1.0.0 and v1.1.0. Trying to figure it out now.

**Comment by rohansingh** [comment]
Looks like this is due to [`--incompatible_use_specific_tool_files`](bazelbuild/bazel#issues/8531).
